#PBS -l nodes=1:ppn=32
#PBS -j oe
#PBS -o ${out}_chr9.res.txt
#PBS -q batch
#PBS -V
cd $PBS_O_WORKDIR

hicPlotMatrix -m ${inp_h5} --outFileName ${out}.chr9.contact.png \
--chromosomeOrder chr9 \
--log \
--vMin ${vmin} --vMax ${vmax} \
--clearMaskedBins \
--colorMap Reds \
--fontsize 10 \
--dpi 300 \
--scoreName "Contacts"

#--title "shHNRNPU" \
#--chromosomeOrder chr1 chr2 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 chr20 chr21 chr22 chrX chrY
